### ISSUE TITLE
Google Calendar Api-Time out exception on IIS

### ISSUE THREAD

**Issue by togreatmind** [google/calendar-connectors#72]
Hello,
I created the sample Asp.net application to get all the calender and add event in a calendar.My Application is working fine when i run it using Visual Studio it successfully load the page,show all calendar info, add event in calendar.But when i deploy the app on IIS, page never load and it gives the "Request timed out" exception.Kindly help

Following is the code

private CalendarService InitGoogleService()
{
UserCredential credential;
string path = Server.MapPath("~") + @"\GCSc.json";
string credPath = Server.MapPath("~") + @"\Calendar_Data";
credential = GoogleWebAuthorizationBroker.AuthorizeAsync(new ClientSecrets
{
ClientId = "My Client Id",
ClientSecret = "My Client Secret"
}, Scopes, "user", CancellationToken.None, new Google.Apis.Util.Store.FileDataStore(credPath)).Result;

        CalendarService service = new CalendarService(new BaseClientService.Initializer()
        {
            HttpClientInitializer = credential,
            ApplicationName = ApplicationName,
        });
        return service;
    }

**Comment by eesheesh** [comment]
The Google Calendar API code in this repo uses the now deprecated Calendar API v2. You should [consult the documentation for the new API](https://developers.google.com/google-apps/calendar/quickstart/dotnet).

The calendar connectors are no longer supported, the code is only here for reference.
